services:
  - type: web
    name: project
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate"
    startCommand: "gunicorn project_name.wsgi:application --preload"
    staticPublishPath: staticfiles
